name: Generate Dinosaur

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Dinosaur
        uses: TejasQ/add-dino@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
